-- 店舗×任意の西暦月（YYYY-MM）ごとの手入力売上。前年固定テーブルを置き換え。

create table if not exists public.line_sales_manual_month_gross (
  id bigint generated by default as identity primary key,
  store_partition_key text not null,
  sales_month text not null,
  gross_sales_yen bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint line_sales_manual_month_fmt_chk
    check (sales_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  constraint line_sales_manual_gross_yen_chk check (gross_sales_yen >= 0),
  constraint line_sales_manual_month_store_month_uidx unique (store_partition_key, sales_month)
);

create index if not exists line_sales_manual_month_sales_month_idx
  on public.line_sales_manual_month_gross (sales_month desc);

alter table public.line_sales_manual_month_gross enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'line_sales_manual_month_gross'
      and policyname = 'Service role line_sales_manual_month_gross'
  ) then
    create policy "Service role line_sales_manual_month_gross"
      on public.line_sales_manual_month_gross
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;

-- 旧テーブルがある環境のみ: reference_month の前年同月へ寄せて移行
do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'line_sales_month_prior_year_manual'
  ) then
    insert into public.line_sales_manual_month_gross (
      store_partition_key,
      sales_month,
      gross_sales_yen,
      created_at,
      updated_at
    )
    select
      p.store_partition_key,
      to_char((p.reference_month || '-01')::date - interval '1 year', 'YYYY-MM'),
      p.prior_year_gross_yen,
      p.created_at,
      p.updated_at
    from public.line_sales_month_prior_year_manual p
    on conflict (store_partition_key, sales_month) do update
    set
      gross_sales_yen = excluded.gross_sales_yen,
      updated_at = excluded.updated_at;
  end if;
end;
$$;

drop table if exists public.line_sales_month_prior_year_manual;
