create table if not exists public.ikyu_reservation_visit_summaries (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  visit_count integer not null default 0,
  last_visit_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (customer_name, customer_phone)
);

create index if not exists ikyu_reservation_visit_summaries_updated_at_idx
  on public.ikyu_reservation_visit_summaries (updated_at desc);

create table if not exists public.ikyu_reservation_visit_events (
  id bigint generated by default as identity primary key,
  gmail_message_id text not null unique,
  customer_name text not null,
  customer_phone text not null,
  visit_at timestamp with time zone,
  created_at timestamp with time zone not null default now()
);

create index if not exists ikyu_reservation_visit_events_customer_idx
  on public.ikyu_reservation_visit_events (customer_name, customer_phone, created_at desc);

alter table public.ikyu_reservation_visit_summaries enable row level security;
alter table public.ikyu_reservation_visit_events enable row level security;

drop policy if exists "Service role can do everything on ikyu_reservation_visit_summaries"
  on public.ikyu_reservation_visit_summaries;
create policy "Service role can do everything on ikyu_reservation_visit_summaries"
  on public.ikyu_reservation_visit_summaries
  for all
  using (auth.jwt() ->> 'role' = 'service_role');

drop policy if exists "Service role can do everything on ikyu_reservation_visit_events"
  on public.ikyu_reservation_visit_events;
create policy "Service role can do everything on ikyu_reservation_visit_events"
  on public.ikyu_reservation_visit_events
  for all
  using (auth.jwt() ->> 'role' = 'service_role');

create or replace function public.record_ikyu_reservation_visit(
  p_gmail_message_id text,
  p_customer_name text,
  p_customer_phone text,
  p_visit_at timestamp with time zone default null
) returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text;
  v_phone text;
  v_visit_at timestamp with time zone;
  v_row_count integer;
  v_visit_count integer;
begin
  if nullif(trim(p_gmail_message_id), '') is null then
    return null;
  end if;

  v_name := nullif(trim(p_customer_name), '');
  v_phone := nullif(trim(p_customer_phone), '');
  if v_name is null or v_phone is null then
    return null;
  end if;

  v_visit_at := coalesce(p_visit_at, now());

  insert into public.ikyu_reservation_visit_events (
    gmail_message_id,
    customer_name,
    customer_phone,
    visit_at
  ) values (
    p_gmail_message_id,
    v_name,
    v_phone,
    v_visit_at
  )
  on conflict (gmail_message_id) do nothing;

  get diagnostics v_row_count = row_count;

  if v_row_count > 0 then
    insert into public.ikyu_reservation_visit_summaries (
      customer_name,
      customer_phone,
      visit_count,
      last_visit_at,
      created_at,
      updated_at
    ) values (
      v_name,
      v_phone,
      1,
      v_visit_at,
      now(),
      now()
    )
    on conflict (customer_name, customer_phone) do update
      set visit_count = public.ikyu_reservation_visit_summaries.visit_count + 1,
          last_visit_at = greatest(
            coalesce(public.ikyu_reservation_visit_summaries.last_visit_at, excluded.last_visit_at),
            excluded.last_visit_at
          ),
          updated_at = now();
  end if;

  select visit_count
    into v_visit_count
  from public.ikyu_reservation_visit_summaries
  where customer_name = v_name
    and customer_phone = v_phone
  limit 1;

  return coalesce(v_visit_count, 0);
end;
$$;

grant execute on function public.record_ikyu_reservation_visit(text, text, text, timestamp with time zone) to service_role;
