-- Per-document viewer permissions.
-- If a document has no rows in this table, it is treated as publicly viewable.

create table if not exists public.line_search_document_viewers (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.line_search_documents(id) on delete cascade,
  line_user_id text not null,
  created_at timestamptz not null default now(),
  unique (document_id, line_user_id)
);

create index if not exists line_search_document_viewers_document_idx
  on public.line_search_document_viewers (document_id);

create index if not exists line_search_document_viewers_user_idx
  on public.line_search_document_viewers (line_user_id);

alter table public.line_search_document_viewers enable row level security;

drop policy if exists "Service role can do everything on line_search_document_viewers"
  on public.line_search_document_viewers;

create policy "Service role can do everything on line_search_document_viewers"
  on public.line_search_document_viewers
  for all
  to service_role
  using (true)
  with check (true);
