-- 店舗休日を行単位で永続化（jsonb 列のみだと環境差で読み取りが空になる問題を回避）

create table if not exists public.line_sales_month_store_closed_days (
  id bigint generated by default as identity primary key,
  store_partition_key text not null,
  target_month text not null,
  closed_on date not null,
  created_at timestamptz not null default now(),
  constraint line_sales_month_store_closed_days_target_month_chk
    check (target_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  constraint line_sales_month_store_closed_days_store_month_date_uidx
    unique (store_partition_key, target_month, closed_on)
);

create index if not exists line_sales_month_store_closed_days_lookup_idx
  on public.line_sales_month_store_closed_days (store_partition_key, target_month);

alter table public.line_sales_month_store_closed_days enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'line_sales_month_store_closed_days'
      and policyname = 'Service role can do everything on line_sales_month_store_closed_days'
  ) then
    create policy "Service role can do everything on line_sales_month_store_closed_days"
      on public.line_sales_month_store_closed_days
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;

-- 既存 jsonb から移行（列がある環境のみ）
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'line_sales_month_budgets'
      and column_name = 'store_closed_dates'
  ) then
    insert into public.line_sales_month_store_closed_days (store_partition_key, target_month, closed_on)
    select
      b.store_partition_key,
      b.target_month,
      t.elem::date
    from public.line_sales_month_budgets b
    cross join lateral jsonb_array_elements_text(
      case
        when b.store_closed_dates is null then '[]'::jsonb
        when jsonb_typeof(b.store_closed_dates) = 'array' then b.store_closed_dates
        else '[]'::jsonb
      end
    ) as t(elem)
    where t.elem ~ '^\d{4}-\d{2}-\d{2}$'
    on conflict (store_partition_key, target_month, closed_on) do nothing;
  end if;
end;
$$;
