-- Webhook 専用の LINE 送信ログ（line-webhook の reply/push 成否）

CREATE TABLE IF NOT EXISTS public.line_webhook_delivery_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    jst_hour integer NOT NULL CHECK (jst_hour >= 0 AND jst_hour <= 23),
    status text NOT NULL,
    reason text,
    method text NOT NULL CHECK (method IN ('reply', 'push')),
    context text NOT NULL DEFAULT '',
    line_send_attempted boolean NOT NULL DEFAULT true,
    line_send_success boolean NOT NULL DEFAULT false,
    line_http_status integer,
    target_room_id text,
    details jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS line_webhook_delivery_logs_created_at_idx
    ON public.line_webhook_delivery_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS line_webhook_delivery_logs_target_room_id_idx
    ON public.line_webhook_delivery_logs (target_room_id);

ALTER TABLE public.line_webhook_delivery_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role can do everything on line_webhook_delivery_logs"
    ON public.line_webhook_delivery_logs;

CREATE POLICY "Service role can do everything on line_webhook_delivery_logs"
    ON public.line_webhook_delivery_logs
    FOR ALL
    USING (auth.jwt() ->> 'role' = 'service_role');

-- 旧 summary_delivery_logs に残っている Webhook 行を移行（存在する場合のみ）
INSERT INTO public.line_webhook_delivery_logs (
    created_at,
    jst_hour,
    status,
    reason,
    method,
    context,
    line_send_attempted,
    line_send_success,
    line_http_status,
    target_room_id,
    details
)
SELECT
    s.run_at,
    s.jst_hour,
    s.status,
    s.reason,
    CASE
        WHEN (s.details ->> 'method') IN ('reply', 'push') THEN (s.details ->> 'method')
        ELSE 'reply'
    END,
    COALESCE(NULLIF(trim(s.details ->> 'context'), ''), 'migrated'),
    s.line_send_attempted,
    s.line_send_success,
    s.line_http_status,
    s.target_room_id,
    COALESCE(s.details, '{}'::jsonb)
FROM public.summary_delivery_logs s
WHERE s.details ->> 'source' = 'line-webhook';

DELETE FROM public.summary_delivery_logs
WHERE details ->> 'source' = 'line-webhook';

-- ストレージ統計 RPC にテーブルを追加
CREATE OR REPLACE FUNCTION public.get_storage_usage_stats()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  db_size_bytes bigint;
  managed_total_bytes bigint;
  managed_tables jsonb;
BEGIN
  SELECT pg_database_size(current_database())
    INTO db_size_bytes;

  SELECT coalesce(sum(pg_total_relation_size(c.oid)), 0)
    INTO managed_total_bytes
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relkind = 'r'
    AND c.relname IN (
      'line_messages',
      'line_message_media',
      'line_search_documents',
      'summary_delivery_logs',
      'line_webhook_delivery_logs',
      'room_summary_settings',
      'summary_settings',
      'calendar_pending_confirmations'
    );

  SELECT coalesce(
      jsonb_agg(
        jsonb_build_object(
          'table_name', c.relname,
          'size_bytes', pg_total_relation_size(c.oid),
          'size_pretty', pg_size_pretty(pg_total_relation_size(c.oid))
        )
        ORDER BY pg_total_relation_size(c.oid) DESC
      ),
      '[]'::jsonb
    )
    INTO managed_tables
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relkind = 'r'
    AND c.relname IN (
      'line_messages',
      'line_message_media',
      'line_search_documents',
      'summary_delivery_logs',
      'line_webhook_delivery_logs',
      'room_summary_settings',
      'summary_settings',
      'calendar_pending_confirmations'
    );

  RETURN jsonb_build_object(
    'database_size_bytes', db_size_bytes,
    'database_size_pretty', pg_size_pretty(db_size_bytes),
    'managed_tables_total_bytes', managed_total_bytes,
    'managed_tables_total_pretty', pg_size_pretty(managed_total_bytes),
    'managed_tables', managed_tables
  );
END;
$$;

REVOKE ALL ON FUNCTION public.get_storage_usage_stats() FROM public;
GRANT EXECUTE ON FUNCTION public.get_storage_usage_stats() TO service_role;
