CREATE TABLE IF NOT EXISTS public.calendar_update_pending_targets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_key text NOT NULL,
    room_id text NOT NULL,
    user_id text,
    target_events_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'resolved', 'cancelled', 'expired', 'superseded')),
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    resolved_at timestamp with time zone
);

CREATE UNIQUE INDEX IF NOT EXISTS calendar_update_pending_targets_active_key_idx
    ON public.calendar_update_pending_targets (conversation_key)
    WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS calendar_update_pending_targets_room_user_idx
    ON public.calendar_update_pending_targets (room_id, user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS calendar_update_pending_targets_status_expires_idx
    ON public.calendar_update_pending_targets (status, expires_at);

ALTER TABLE public.calendar_update_pending_targets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role can do everything on calendar_update_pending_targets"
    ON public.calendar_update_pending_targets;

CREATE POLICY "Service role can do everything on calendar_update_pending_targets"
    ON public.calendar_update_pending_targets
    FOR ALL
    USING (auth.jwt() ->> 'role' = 'service_role');
