CREATE TABLE IF NOT EXISTS public.calendar_pending_confirmations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_key text NOT NULL,
    room_id text NOT NULL,
    user_id text,
    source_text text NOT NULL,
    title text NOT NULL,
    date text NOT NULL,
    time text NOT NULL,
    duration_min integer NOT NULL CHECK (duration_min > 0 AND duration_min <= 720),
    confidence double precision NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    reason text,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'confirmed', 'cancelled', 'expired', 'superseded')),
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    resolved_at timestamp with time zone
);

CREATE UNIQUE INDEX IF NOT EXISTS calendar_pending_confirmations_active_key_idx
    ON public.calendar_pending_confirmations (conversation_key)
    WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS calendar_pending_confirmations_room_user_idx
    ON public.calendar_pending_confirmations (room_id, user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS calendar_pending_confirmations_status_expires_idx
    ON public.calendar_pending_confirmations (status, expires_at);

ALTER TABLE public.calendar_pending_confirmations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role can do everything on calendar_pending_confirmations"
    ON public.calendar_pending_confirmations;

CREATE POLICY "Service role can do everything on calendar_pending_confirmations"
    ON public.calendar_pending_confirmations
    FOR ALL
    USING (auth.jwt() ->> 'role' = 'service_role');
