create table if not exists public.gmail_reservation_alert_logs (
  id bigint generated by default as identity primary key,
  gmail_message_id text not null unique,
  gmail_thread_id text,
  gmail_subject text,
  gmail_from text,
  gmail_internal_date timestamp with time zone,
  line_target_room_id text not null,
  line_message_sent_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now()
);

create index if not exists gmail_reservation_alert_logs_created_at_idx
  on public.gmail_reservation_alert_logs (created_at desc);

create index if not exists gmail_reservation_alert_logs_target_room_idx
  on public.gmail_reservation_alert_logs (line_target_room_id, created_at desc);

alter table public.gmail_reservation_alert_logs enable row level security;

drop policy if exists "Service role can do everything on gmail_reservation_alert_logs"
  on public.gmail_reservation_alert_logs;

create policy "Service role can do everything on gmail_reservation_alert_logs"
  on public.gmail_reservation_alert_logs
  for all
  using (auth.jwt() ->> 'role' = 'service_role');
