create table if not exists public.line_message_media (
  id bigint generated by default as identity primary key,
  message_id uuid not null references public.line_messages(id) on delete cascade,
  line_message_id text not null,
  room_id text not null,
  user_id text,
  media_type text not null check (media_type in ('image', 'video', 'audio', 'file')),
  storage_bucket text not null default 'line-media',
  storage_path text not null,
  original_file_name text,
  mime_type text,
  file_size_bytes bigint not null default 0,
  created_at timestamp with time zone not null default now()
);

create unique index if not exists line_message_media_line_message_id_uidx
  on public.line_message_media(line_message_id);

create index if not exists line_message_media_room_created_idx
  on public.line_message_media(room_id, created_at desc);

create index if not exists line_message_media_created_idx
  on public.line_message_media(created_at desc);

alter table public.line_message_media enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'line_message_media'
      and policyname = 'Service role can do everything on line_message_media'
  ) then
    create policy "Service role can do everything on line_message_media"
      on public.line_message_media
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;

insert into storage.buckets (id, name, public, file_size_limit)
values ('line-media', 'line-media', false, 52428800)
on conflict (id) do update
set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit;
