create table if not exists public.line_receipt_entries (
  id bigint generated by default as identity primary key,
  message_id uuid not null references public.line_messages(id) on delete cascade,
  line_message_id text not null,
  room_id text not null,
  user_id text,
  sender_display_name text,
  store_name text,
  receipt_date_text text,
  receipt_date date,
  net_sales_yen bigint,
  tax_amount_yen bigint,
  gross_sales_yen bigint,
  party_count integer,
  guest_count integer,
  unit_price_yen bigint,
  summary_text text,
  raw_payload jsonb,
  created_at timestamp with time zone not null default now()
);

create unique index if not exists line_receipt_entries_line_message_id_uidx
  on public.line_receipt_entries(line_message_id);

create index if not exists line_receipt_entries_room_created_idx
  on public.line_receipt_entries(room_id, created_at desc);

create index if not exists line_receipt_entries_receipt_date_idx
  on public.line_receipt_entries(receipt_date desc);

alter table public.line_receipt_entries enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'line_receipt_entries'
      and policyname = 'Service role can do everything on line_receipt_entries'
  ) then
    create policy "Service role can do everything on line_receipt_entries"
      on public.line_receipt_entries
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;

create table if not exists public.line_receipt_mid_reports (
  id bigint generated by default as identity primary key,
  report_month date not null,
  room_id text not null,
  period_start_jst date not null,
  period_end_jst date not null,
  trigger_type text not null check (trigger_type in ('day15_post', 'day15_fallback')),
  trigger_line_message_id text,
  receipt_count integer not null default 0,
  total_gross_sales_yen bigint not null default 0,
  total_party_count integer not null default 0,
  total_guest_count integer not null default 0,
  avg_gross_sales_yen bigint,
  avg_party_count numeric(12, 2),
  avg_guest_count numeric(12, 2),
  sent_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now()
);

create unique index if not exists line_receipt_mid_reports_room_month_uidx
  on public.line_receipt_mid_reports(room_id, report_month);

create index if not exists line_receipt_mid_reports_month_idx
  on public.line_receipt_mid_reports(report_month desc);

alter table public.line_receipt_mid_reports enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'line_receipt_mid_reports'
      and policyname = 'Service role can do everything on line_receipt_mid_reports'
  ) then
    create policy "Service role can do everything on line_receipt_mid_reports"
      on public.line_receipt_mid_reports
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;

create or replace function public.invoke_receipt_midreport_cron()
returns void
language plpgsql
security definer
as $$
declare
  edge_function_url text;
  cron_auth_token text;
  request_id bigint;
begin
  edge_function_url := nullif(current_setting('custom.receipt_midreport_edge_function_url', true), '');
  if edge_function_url is null then
    edge_function_url := 'https://jhpmzqxqvapdkyvvhyra.supabase.co/functions/v1/receipt-midreport-cron';
  end if;

  cron_auth_token := public.resolve_edge_cron_auth_token();
  if cron_auth_token is null then
    raise warning 'invoke_receipt_midreport_cron skipped: cron auth token is not configured';
    return;
  end if;

  select net.http_post(
    url := edge_function_url,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || cron_auth_token
    )
  ) into request_id;

  raise log 'invoke_receipt_midreport_cron: Triggered Edge Function at %, request_id=%', edge_function_url, request_id;
end;
$$;

do $$
begin
  begin
    perform cron.unschedule('receipt-midreport-cron-job');
  exception
    when others then
      null;
  end;
end
$$;

select cron.schedule(
  'receipt-midreport-cron-job',
  '* * * * *',
  $$ select public.invoke_receipt_midreport_cron(); $$
);
