create table if not exists public.line_search_documents (
  id bigint generated by default as identity primary key,
  room_id text,
  room_name text,
  storage_bucket text not null default 'line-documents',
  storage_path text not null,
  original_file_name text not null,
  mime_type text not null,
  file_size_bytes bigint not null default 0,
  extracted_text text not null default '',
  source text not null default 'manual_upload',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint line_search_documents_source_check
    check (source in ('manual_upload', 'line_import', 'system_import'))
);

create unique index if not exists line_search_documents_storage_path_uidx
  on public.line_search_documents(storage_path);

create index if not exists line_search_documents_room_created_idx
  on public.line_search_documents(room_id, created_at desc);

create index if not exists line_search_documents_created_idx
  on public.line_search_documents(created_at desc);

alter table public.line_search_documents enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'line_search_documents'
      and policyname = 'Service role can do everything on line_search_documents'
  ) then
    create policy "Service role can do everything on line_search_documents"
      on public.line_search_documents
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;

insert into storage.buckets (id, name, public, file_size_limit)
values ('line-documents', 'line-documents', false, 52428800)
on conflict (id) do update
set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit;

create or replace function public.get_line_document_usage_stats(
  filter_room_id text default null
)
returns table (
  total_files bigint,
  total_bytes bigint
)
language sql
security definer
set search_path = public
as $$
  select
    count(*)::bigint as total_files,
    coalesce(sum(d.file_size_bytes), 0)::bigint as total_bytes
  from public.line_search_documents d
  where (filter_room_id is null or filter_room_id = '' or d.room_id = filter_room_id);
$$;

revoke all on function public.get_line_document_usage_stats(text) from public;
grant execute on function public.get_line_document_usage_stats(text) to service_role;

create or replace function public.get_storage_usage_stats()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  db_size_bytes bigint;
  managed_total_bytes bigint;
  managed_tables jsonb;
begin
  select pg_database_size(current_database())
    into db_size_bytes;

  select coalesce(sum(pg_total_relation_size(c.oid)), 0)
    into managed_total_bytes
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relkind = 'r'
    and c.relname in (
      'line_messages',
      'line_message_media',
      'line_search_documents',
      'summary_delivery_logs',
      'room_summary_settings',
      'summary_settings',
      'calendar_pending_confirmations'
    );

  select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'table_name', c.relname,
          'size_bytes', pg_total_relation_size(c.oid),
          'size_pretty', pg_size_pretty(pg_total_relation_size(c.oid))
        )
        order by pg_total_relation_size(c.oid) desc
      ),
      '[]'::jsonb
    )
    into managed_tables
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relkind = 'r'
    and c.relname in (
      'line_messages',
      'line_message_media',
      'line_search_documents',
      'summary_delivery_logs',
      'room_summary_settings',
      'summary_settings',
      'calendar_pending_confirmations'
    );

  return jsonb_build_object(
    'database_size_bytes', db_size_bytes,
    'database_size_pretty', pg_size_pretty(db_size_bytes),
    'managed_tables_total_bytes', managed_total_bytes,
    'managed_tables_total_pretty', pg_size_pretty(managed_total_bytes),
    'managed_tables', managed_tables
  );
end;
$$;

revoke all on function public.get_storage_usage_stats() from public;
grant execute on function public.get_storage_usage_stats() to service_role;

alter table public.summary_settings
  alter column message_retention_days set default 365;

update public.summary_settings
set message_retention_days = 365
where message_retention_days is null
   or message_retention_days not in (0, 60, 120, 180, 365, 730, 1095);

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'summary_settings_message_retention_days_check'
      and conrelid = 'public.summary_settings'::regclass
  ) then
    alter table public.summary_settings
      drop constraint summary_settings_message_retention_days_check;
  end if;

  alter table public.summary_settings
    add constraint summary_settings_message_retention_days_check
    check (message_retention_days in (0, 60, 120, 180, 365, 730, 1095));
end;
$$;
