-- 売上分析（analytics）用: 店舗×対象月ごとの「前年同月総売上」の手入力（レシートが無い場合の前年比用）

create table if not exists public.line_sales_month_prior_year_manual (
  id bigint generated by default as identity primary key,
  store_partition_key text not null,
  reference_month text not null,
  prior_year_gross_yen bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint line_sales_prior_year_reference_month_chk
    check (reference_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  constraint line_sales_prior_year_gross_chk check (prior_year_gross_yen >= 0),
  constraint line_sales_prior_year_store_month_uidx unique (store_partition_key, reference_month)
);

create index if not exists line_sales_prior_year_reference_month_idx
  on public.line_sales_month_prior_year_manual (reference_month desc);

alter table public.line_sales_month_prior_year_manual enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'line_sales_month_prior_year_manual'
      and policyname = 'Service role can do everything on line_sales_month_prior_year_manual'
  ) then
    create policy "Service role can do everything on line_sales_month_prior_year_manual"
      on public.line_sales_month_prior_year_manual
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;
