CREATE TABLE IF NOT EXISTS public.message_search_expand_pending_confirmations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_key text NOT NULL,
    room_id text NOT NULL,
    user_id text,
    keyword text NOT NULL,
    search_days integer NOT NULL
        CHECK (search_days IN (0, 60, 120, 180, 365, 730, 1095)),
    search_scope text NOT NULL
        CHECK (search_scope IN ('current_room', 'all_rooms')),
    retention_adjusted boolean NOT NULL DEFAULT false,
    stage_windows jsonb NOT NULL,
    next_ring_k integer NOT NULL
        CHECK (next_ring_k >= 0),
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'confirmed', 'cancelled', 'expired', 'superseded')),
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    resolved_at timestamp with time zone
);

CREATE UNIQUE INDEX IF NOT EXISTS message_search_expand_pending_active_key_idx
    ON public.message_search_expand_pending_confirmations (conversation_key)
    WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS message_search_expand_pending_room_user_idx
    ON public.message_search_expand_pending_confirmations (room_id, user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS message_search_expand_pending_status_expires_idx
    ON public.message_search_expand_pending_confirmations (status, expires_at);

ALTER TABLE public.message_search_expand_pending_confirmations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "sr_all_msg_search_expand_pending"
    ON public.message_search_expand_pending_confirmations;

DROP POLICY IF EXISTS "Service role can do everything on message_search_expand_pending"
    ON public.message_search_expand_pending_confirmations;

DROP POLICY IF EXISTS "Service role can do everything on message_search_expand_pending_confirmations"
    ON public.message_search_expand_pending_confirmations;

CREATE POLICY "sr_all_msg_search_expand_pending"
    ON public.message_search_expand_pending_confirmations
    FOR ALL
    USING (auth.jwt() ->> 'role' = 'service_role');
