-- 売上分析（analytics）用: 店舗×月の月間予算。admin-api（service_role）のみ RLS 経由で更新

create table if not exists public.line_sales_month_budgets (
  id bigint generated by default as identity primary key,
  store_partition_key text not null,
  target_month text not null,
  budget_yen bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint line_sales_month_budgets_target_month_chk
    check (target_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  constraint line_sales_month_budgets_budget_yen_chk check (budget_yen > 0),
  constraint line_sales_month_budgets_store_month_uidx unique (store_partition_key, target_month)
);

create index if not exists line_sales_month_budgets_month_idx
  on public.line_sales_month_budgets (target_month desc);

alter table public.line_sales_month_budgets enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'line_sales_month_budgets'
      and policyname = 'Service role can do everything on line_sales_month_budgets'
  ) then
    create policy "Service role can do everything on line_sales_month_budgets"
      on public.line_sales_month_budgets
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;
