CREATE TABLE IF NOT EXISTS public.summary_delivery_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_at timestamp with time zone NOT NULL DEFAULT now(),
    jst_hour integer NOT NULL CHECK (jst_hour >= 0 AND jst_hour <= 23),
    status text NOT NULL,
    reason text,
    should_send_overall boolean NOT NULL DEFAULT false,
    rooms_targeted integer NOT NULL DEFAULT 0,
    messages_in_queue integer NOT NULL DEFAULT 0,
    messages_marked_processed integer NOT NULL DEFAULT 0,
    line_send_attempted boolean NOT NULL DEFAULT false,
    line_send_success boolean NOT NULL DEFAULT false,
    line_http_status integer,
    target_room_id text,
    details jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS summary_delivery_logs_run_at_idx
    ON public.summary_delivery_logs (run_at DESC);

CREATE INDEX IF NOT EXISTS summary_delivery_logs_status_idx
    ON public.summary_delivery_logs (status);

ALTER TABLE public.summary_delivery_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role can do everything on summary_delivery_logs"
    ON public.summary_delivery_logs;

CREATE POLICY "Service role can do everything on summary_delivery_logs"
    ON public.summary_delivery_logs
    FOR ALL
    USING (auth.jwt() ->> 'role' = 'service_role');
