create table if not exists public.haccp_schedule_calendar_registrations (
  id bigint generated by default as identity primary key,
  line_message_id text not null,
  room_id text not null,
  user_id text,
  sender_display_name text,
  original_file_name text,
  store_name text not null,
  event_date date not null,
  calendar_event_id text,
  created_at timestamptz not null default now()
);

create unique index if not exists haccp_schedule_calendar_registrations_unique
  on public.haccp_schedule_calendar_registrations (line_message_id, store_name, event_date);

create index if not exists haccp_schedule_calendar_registrations_event_date_idx
  on public.haccp_schedule_calendar_registrations (event_date desc);

alter table public.haccp_schedule_calendar_registrations enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'haccp_schedule_calendar_registrations'
      and policyname = 'Service role can do everything on haccp_schedule_calendar_registrations'
  ) then
    create policy "Service role can do everything on haccp_schedule_calendar_registrations"
      on public.haccp_schedule_calendar_registrations
      for all
      using (auth.jwt() ->> 'role' = 'service_role');
  end if;
end;
$$;
